### ISSUE TITLE
"Paper not released by department" not shown on the Windows version for certain modules.

### ISSUE THREAD

**Issue by xbili** [nusmodifications/nus-exams-downloader#2]
To reproduce this on Windows: 
1. Head to a module that has unreleased papers (e.g. BN2201)
2. Start download
3. It shows "Downloading 5 of 5" instead of "Paper not released by department"

Here's a screenshot provided by a friend:
![11101357_10153309073133112_846078046_n](https://cloud.githubusercontent.com/assets/4846457/7269004/b2f41f40-e901-11e4-9860-fdf5fb5a62af.jpg)

Here're the available papers for BN2201, which are not released.
![screen shot 2015-04-22 at 3 09 50 pm](https://cloud.githubusercontent.com/assets/4846457/7269013/bfa3407c-e901-11e4-9353-3ed7b3dd7f76.png)

Seems to work fine on Mac though. Need a Windows user to verify this. :)

**Comment by Ohohcakester** [comment]
It seems I had built an older version of the code for windows. I'll rebuild it and put it up.

**Comment by xbili** [comment]
@Ohohcakester That's awesome, thanks! :D
