### ISSUE TITLE
Wrong Username/Password for certain special characters

### ISSUE THREAD

**Issue by shuchang91** [nusmodifications/nus-exams-downloader#3]
Getting a wrong username/password message for passwords with a % as the special character. Suspect it's a html issue. Need to detect and change to %25 maybe?

**Comment by yangshun** [comment]
Wow @shuchang91  we never thought of that. Thanks for bringing it up.

Seeing that you know how to fix problem, would you mind making a pull request? (:

**Comment by shuchang91** [comment]
@yangshun unfortunately I don't know a single line of python :/ Only realised the error as my password was affected and %25 worked.

**Comment by yangshun** [comment]
Thanks @ashrayjain  (:
